---
title: "Jaesa Rogers CV"
author: Jaesa Rogers
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['css/styles.css', 'resume']
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(glue)
library(tidyverse)

# Set this to true to have links turned into footnotes at the end of the document
PDF_EXPORT <- FALSE

# Holds all the links that were inserted for placement at the end
links <- c()

source('parsing_functions.R')

# Load csv with position info
position_data <- read_csv('positions.csv')
```


```{r}
# When in export mode the little dots are unaligned, so fix that. 
if(PDF_EXPORT){
  cat("
  <style>
  :root{
    --decorator-outer-offset-left: -6.5px;
  }
  </style>")
}
```


Aside
================================================================================




```{r}
# When in export mode the little dots are unaligned, so fix that. 
if(PDF_EXPORT){
  cat("View this CV online with links at _nickstrayer.me/cv_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/nstrayer/cv/raw/master/strayer_cv.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------


- <i class="fa fa-envelope"></i> nick.strayer@gmail.com
- <i class="fa fa-twitter"></i> NicholasStrayer
- <i class="fa fa-github"></i> github.com/nstrayer
- <i class="fa fa-link"></i> [nickstrayer.me](http://nickstrayer.me/)
- <i class="fa fa-phone"></i> (734) 645-0110



Technical Skills {#skills}
--------------------------------------------------------------------------------




```{r}
skills <- tribble(
  ~skill,               ~level,
  "Microsoft Excel",     5,
  "Microsoft PowerPoint",4.5,
  "Tableau",             3,
  "R",                   3,
  "Microsoft Access",    2,
  "SQL",                 2,
  
)
build_skill_bars(skills)
```


Soft Skills {#skills2}
--------------------------------------------------------------------------------


```{r}
skills2 <- tribble(
~skill,                              ~level,
  "Collaboration with others",              5,
  "8 years comedic improv",                 5,  
  "Public Speaking and communication",      4.5,
  "Organizational Leadership",              4,
 
  
)
build_skill_bars(skills2)




Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

The source code is available at [github.com/nstrayer/cv](https://github.com/nstrayer/cv).

Last updated on `r Sys.Date()`.




Main
================================================================================

Nick Strayer {#title}
--------------------------------------------------------------------------------


```{r}
intro_text <- "I am currently a Data Analyst at ASU International Development and I am interested in continuing a career of transforming data into visualizations within an industry that works for the greater good. 
I have a passion for organized compassion."

cat(sanitize_links(intro_text))
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'education')
```



Industry Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

::: aside
I have worked in a variety of roles ranging from journalist to software engineer to data scientist. I like collaborative environments where I can learn from my peers. 
:::

```{r}
print_section(position_data, 'industry_positions')
```

<br>
<br>
<br>

Leadership Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------


```{r}
print_section(position_data, 'leadership_positions')
```




```{r}
if(PDF_EXPORT){
  cat("
  
Links {data-icon=link}
--------------------------------------------------------------------------------

<br>


")
  
  walk2(links, 1:length(links), function(link, index){
    print(glue('{index}. {link}'))
  })
}
```


