---
title: "Jaesa Roger's Resume"
author: Jaesa Rogers
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['css/custom_resume.css', 'css/styles.css', 'resume']
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
---


```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)
library( pagedown )
library( glue )
library( tidyverse )
library( pander )

# Set this to true to have links turned into footnotes at the end of the document
PDF_EXPORT <- FALSE

# Holds all the links that were inserted for placement at the end
links <- c()

source('parsing_functions.R')


# First let's get the data, filtering to only the items tagged as
# Resume items
position_data <- read_csv('positions.csv') %>% 
  filter(in_resume) %>% 
  mutate(
    # Build some custom sections by collapsing others
    section = case_when(
      section %in% c('industry_positions', 'leadership_positions') ~ 'positions', 
     
      TRUE ~ section
    )
  ) 

```


Aside
================================================================================



Contact {#contact}
--------------------------------------------------------------------------------



- <i class="fa fa-envelope"></i> jaesa.rogers@asu.edu
- <i class="fa fa-github"></i> github.com/JaesaR
- <i class="fa fa-phone"></i> (775) 303-4737



Technical Skills {#skills}
--------------------------------------------------------------------------------




```{r}
skills <- tribble(
  ~skill,               ~level,
  "Microsoft Excel",     5,
  "Microsoft PowerPoint",4.5,
  "Tableau",             3,
  "R",                   3,
  "Microsoft Access",    2,
  "SQL",                 2,
  
)
build_skill_bars(skills)

```


Soft Skills {#skills2}
--------------------------------------------------------------------------------


```{r}
skills2 <- tribble(
~skill,                              ~level,
  "Collaboration with others",              5,
  "8 years comedic improv",                 5,  
  "Public Speaking and communication",      4.5,
  "Organizational Leadership",              4,

 
  
)
build_skill_bars(skills2)
```

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made w/ [**pagedown**](https://github.com/rstudio/pagedown). 

Source code: [github.com/nstrayer/cv](https://github.com/nstrayer/cv).

Last updated on `r Sys.Date()`.




Main
================================================================================

Jaesa Rogers {#title}
--------------------------------------------------------------------------------

```{r}
intro_text <- "I am currently a Data Analyst at ASU International Development and I am interested in continuing a career of transforming data into visualizations within an industry that works for the greater good. 
I have a passion for organized compassion."


cat(sanitize_links(intro_text))
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
position_data %>% print_section('education')
```



Selected Positions {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
position_data %>% print_section('positions')
```
